"use client";
import { useEffect, useMemo, useState } from "react";

export default function HTMLAppletRenderer({ htmlCode }: { htmlCode: string }) {
  // Strip ```html ... ``` fences if the model returned them.
  const cleanHtml = useMemo(() => {
    const match = htmlCode.match(/```html([\s\S]*?)```/);
    return match ? match[1].trim() : htmlCode;
  }, [htmlCode]);

  // Build a blob: URL for the iframe and revoke it when the HTML changes.
  const [blobUrl, setBlobUrl] = useState<string | null>(null);
  useEffect(() => {
    if (!cleanHtml) {
      setBlobUrl(null);
      return;
    }
    const url = URL.createObjectURL(new Blob([cleanHtml], { type: "text/html" }));
    setBlobUrl(url);
    return () => {
      URL.revokeObjectURL(url);
    };
  }, [cleanHtml]);

  return (
    <div style={{ width: "100%", height: "100%", minHeight: "500px", position: "relative" }}
         className="rounded-[24px] overflow-hidden shadow-sm border border-slate-200 bg-black">
      {!blobUrl && (
        <div className="absolute inset-0 flex items-center justify-center bg-black/80 z-10">
          <div className="text-white text-sm animate-pulse">Loading simulation...</div>
        </div>
      )}
      {blobUrl && (
        // The HTML in this iframe is generated by the model and may contain
        // arbitrary JS / fetch calls. A blob: URL inherits the parent origin,
        // so without a sandbox attribute that JS could read this app's cookies,
        // localStorage, and call same-origin /api/* routes.
        //
        // `allow-scripts` lets the simulation run; we deliberately do NOT
        // include `allow-same-origin`, which forces the iframe into a unique
        // opaque origin and cuts it off from anything in this app.
        <iframe
          src={blobUrl}
          sandbox="allow-scripts"
          style={{ width: "100%", height: "100%", minHeight: "500px", border: "none", display: "block" }}
          allow="accelerometer; gyroscope"
          title="Interactive AI Applet"
        />
      )}
    </div>
  );
}
